name = "c8a212c1-39"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Note: For Next.js projects, you may need to adapt this configuration
# depending on your specific deployment needs. Next.js projects typically
# require a different entry point and build configuration.

[vars]
# Environment variables go here
# Shopify credentials will be loaded from GitHub repository secrets
# NEXT_PUBLIC_SHOPIFY_SHOP = "your-shop.myshopify.com"
# NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN = "your-storefront-token"

# KV storage configuration (if needed)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 database configuration (if needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"

# R2 storage configuration (if needed)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
# preview_bucket_name = "my-preview-bucket"

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   "example.com/*",
#   "www.example.com/*"
# ]
